apiVersion: v1
kind: Namespace
metadata:
  name: ns-nginx-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deploy
  namespace: ns-nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: nginx:1.19.2
          ports:
            - containerPort: 80
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-svc
  namespace: ns-nginx-app
spec:
  selector:
    app: nginx-app
  ports:
  - port: 8888
    targetPort: 80
    protocol: TCP
  externalIPs:
    - 192.168.27.118
